apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager-pha
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    #automated: {}
    #    prune: true
    #    selfHeal: true
    #    allowEmpty: true
    #managedNamespaceMetadata:
    #  labels:
    #    istio-injection: disabled
    #    goldilocks.fairwinds.com/enabled: "true"
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.17.1
      helm:
        releaseName: cert-manager
        values: |-
          crds:
            enabled: true
            keep: true
          deploymentAnnotations:
            abc: def
    #- repoURL: 'https://github.com/daltontx/k8s-pharmaron.git'
    #  path: apps/cert-manager/base/issuer
    #  targetRevision: main
